name: develop 

on:
  push:
    branches: [master]

jobs:
  job_1:
    name: Setup requirements
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

  job_2:
    name: Build and push to Docker
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: ${{ secrets.REPO_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
    