name: develop 

on:
  push:
    branches: [master]

jobs:
  job_1:
    name: Setup requirements
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

  job_2:
    name: Connect to Docker
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

  job_3:
    name: Get smart tag
    needs: job_2
    id: prepare
    uses: Surgo/docker-smart-tag-action@v1
    with:
      docker_image: ${{ secrets.REPO_NAME }}

  job_4:
    name: Build and push
    needs: job_3
    uses: docker/build-push-action@v2
    with:
      push: true
      tags: ${{ steps.outputs.tag }}
    
  job_5: 
    name: Run build image
    needs: job_4
    uses: docker/build-push-action@v2
    with:
      tags: rhodinemma/reacting:master
      push: false
    uses: addnab/docker-run-action@v3
    with:
      image: rhodinemma/reacting:master
      run: echo "Container runs successfully"