name: develop 

on:
  push:
    branches: [master]

jobs:
  job_1:
    name: Setup requirements
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

  job_2:
    name: Connect to Docker
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

  job_3:
    name: Build and push
    needs: job_2
    runs-on: ubuntu-latest
    steps:
    - name: Build and push docker image
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: ${{ secrets.REPO_NAME }}
    - name: Add tag
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.outputs.tag }}
    
  job_4: 
    name: Run build image
    needs: job_3
    runs-on: ubuntu-latest
    steps:
    - name: Run build image
      uses: docker/build-push-action@v2
      with:
        tags: rhodinemma/reacting:master
        push: false
      
  job_5:
    name: Verify run
    needs: job_4
    runs-on: ubuntu-latest
    steps:
    - name: Verify run
      uses: addnab/docker-run-action@v3
      with:
        image: rhodinemma/reacting:master
        run: echo "Container runs successfully"