name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: ../
          file: docker/dev/Dockerfile
          push: true
          tags: rhodinemma/testing:latest

    # name: Build the Docker image
    #  run: docker build -f Dockerfile -t rhodinemma/reacting .
    # name: Docker Push
    #  run: docker push rhodinemma/reacting:latest
