name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Env variable
env:
  DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file Dockerfile --tag $DOCKERHUB_USER/$REPO_NAME:latest
    - name: Docker Push
      run: docker push $DOCKERHUB_USER/$REPO_NAME:latest
